version: '3.8'
services:
  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    environment:
      - PYTHONUNBUFFERED=1

  nextjs:
    build: ./role_play_app
    ports:
      - "3000:3000"
    volumes:
      - ./role_play_app:/app
    environment:
      - NODE_ENV=development