version: '3.8'
services:
  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  nextjs:
    build: ./role_play_app
    ports:
      - "3000:3000"
    volumes:
      - ./role_play_app:/app
    environment:
      - NODE_ENV=development
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

volumes:
  postgres_data: