version: "3"

services:
  main:
    image: "mcr.microsoft.com/devcontainers/python:3.12-bullseye"
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode
    volumes:
      - ..:/workspace:cached
